version: "3.3"

services:
  scanner:
    image: derhenning/tgtg:latest-alpine ## pre build image from docker hub
    # image: tgtg-scanner:latest                   ## locally build image
    # build:                                       ## build image with compose
    #   context: .
    #   dockerfile: docker/Dockerfile.alpine
    environment:
      # Configuration via environment variables.
      # Basic example using Telegram notifications
      # For more options and details visit https://github.com/Der-Henning/tgtg/wiki/Configuration

      - TGTG_USERNAME=${TGTG_USERNAME} ## your TooGoodToGo login email
      - SLEEP_TIME=60
      - TZ=Europe/Madrid
      - LOCALE=de_DE

      - TELEGRAM=true
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_IDS=${TELEGRAM_CHAT_IDS} ## comma separated list of chat ids
      - 'TELEGRAM_BODY=*${{display_name}}* \n*Available*: ${{items_available}}\n*Price*: ${{price}} ${{currency}}\n*Pickup*: ${{pickupdate}}'
      - TELEGRAM_TIMEOUT=60

    volumes:
      - tokens:/tokens ## volume to save TGTG credentials to reuse on next start up and avoid login mail

volumes:
  tokens:
